SRCS = src/quarry.cpp src/data_set/data_set.cpp src/data_set/example.cpp src/data_set/sparse/sparse_example.cpp src/data_set/features/nominal_feature.cpp src/data_set/features/numeric_feature.cpp src/classifier/classifier.cpp src/classifier/naive_bayes/naive_bayes_classifier.cpp src/metrics/confusion_matrix.cpp src/storage/arff.cpp src/preprocessing/text/text_pipeline.cpp src/preprocessing/text/inplace_processor/porter_stemmer_original.cpp src/preprocessing/text/token_selector/stop_words.cpp src/preprocessing/text/tokeniser/simple_tokeniser.cpp
OBJS = ${SRCS:.cpp=.o}
INCFLAGS = -Isrc
CPPFLAGS += -O3
LIB = libquarry.a

.SUFFIXES:
.SUFFIXES: .cpp .o

.cpp.o :
	$(CXX) $(INCFLAGS) $(CPPFLAGS) -o $@ -c $<

all : $(LIB)

$(LIB) : $(OBJS)
	$(STATIC_LIB) obj/$(LIB) $(OBJS)

test : $(LIB)
	$(CXX) $(INCFLAGS) $(CPPFLAGS) -o obj/test obj/$(LIB) src/test.cpp

clean :
	rm -f $(OBJS)
	rm -f obj/*
